### ISSUE TITLE
Use fontcrunch & latest ttfautohint

### ISSUE THREAD

**Issue by davelab6** [rosettatype/Eczar#10]
Please run https://github.com/googlefonts/fontcrunch on your TTFs before running ttfautohint :)

Also please use the latest ttfautohint :)

**Comment by MrBrezina** [comment]
Thanks.

**Comment by MrBrezina** [comment]
This saves 4KB on WOFF, 2KB on WOFF2, and 3KB on EOT. Is it really worth it?

**Comment by davelab6** [comment]
You seem to have a desktop mindset, looking at a file sitting in stasis on a disk. 

Think about the scale of the web ;)

![1055025549the_social_network_billions2](https://cloud.githubusercontent.com/assets/261579/6028618/e11324ba-abb8-11e4-88e1-f1e5bf18b1c1.jpg)

**Comment by MrBrezina** [comment]
Pff.

**Comment by davelab6** [comment]
:dancers:
