### ISSUE TITLE
Fix shaping for Safari

### ISSUE THREAD

**Issue by davelab6** [rosettatype/eczar#14]
When I use Safari Version 7.1.6 on Mac OS X 10.9 to review http://www.impallari.com/testing/index-devanagari.php#sample_one (you need to click the 'Sample 1' tab link near the top right) then the shaping isn't working

**Comment by MrBrezina** [comment]
Hm. I see this. Are we sure 10.9 supports `dev2` OT layout?

![screen shot 2015-06-17 at 20 53 40](https://cloud.githubusercontent.com/assets/485475/8217104/0c84cf3e-1533-11e5-9b4c-f3f0a62b17b6.png)

**Comment by davelab6** [comment]
Its a problem in a bunch of fonts - eg https://github.com/typeoff/martel_sans/issues/5#issuecomment-112940656 :)

**Comment by MrBrezina** [comment]
My first guess would be that `deva` is used in older Mac OS X systems instead of `dev2`. See my email.

**Comment by davelab6** [comment]
First I made a copy of all the Devanagari fonts currently checked in to GF:

```sh
# in the gf collection
cd github.com/google/fonts.git/ofl;
# make a list of all directories with fonts supporting devanagari
grep devanagari */META* | cut -d\/ -f1 > deva 
# copy all those fonts into a directory
mkdir devaf; 
for i in `cat deva`; do echo $i; cp $i/*ttf devaf/; done;
```

Then I opened Safari and checked them all, and moved them into 2 new directories, working and not-working.

Then I split out all their gsub tables with ttx:

```ssh
ttx -t GSUB */*ttf ;
```

then I searched for fonts with a deva table that work:

```sh
grep \"deva\" */*x | grep "works" | cut -d\/ -f2 | cut -d\- -f1 | sort | uniq | tee deva-works.txt ;
Arya
Bhavuka
Biryani
Dekko
Dinah
EkMukta
Glegoo
Halant
Hind
InknutAntiqua
Jaldi
Kalam
Karma
Khand
Kurale
Laila
Modak
Poppins
PragatiNarrow
Rajdhani
Ranga
RhodiumLibre
RozhaOne
Sarpanch
Sitara
Teko
Tillana
VesperLibre
```
and then for fonts with a deva table that do not work:

```sh
grep \"deva\" */*x | grep "not work" | cut -d\/ -f2 | cut -d\- -f1 | sort | uniq | tee deva-notwork.txt ;
Amita
Asar
Cambay
Khula
Martel
MartelSans
Palanquin
PalanquinDark
Sahitya
Yantramanav
```

And the same for `dev2`:

```sh
grep \"dev2\" */*x | grep "works" | cut -d\/ -f2 | cut -d\- -f1 | sort | uniq | tee dev2-works.txt ;
Arya
Bhavuka
Biryani
Dekko
Dinah
EkMukta
Glegoo
InknutAntiqua
Jaldi
Kurale
Modak
Poppins
PragatiNarrow
RhodiumLibre
Sitara
Tillana
VesperLibre
```

And not works:

```
grep \"dev2\" */*x | grep "not work" | cut -d\/ -f2 | cut -d\- -f1 | sort | uniq | tee dev2-notwork.txt ;
Amita
Asar
Cambay
Eczar
Kadwa
Khula
Martel
MartelSans
Palanquin
PalanquinDark
Sahitya
Sarala
Sumana
Sura
Yantramanav
```

Finally I compared these:

```
meld dev*-works* ;
```

![screen shot 2015-06-17 at 8 32 05 pm](https://cloud.githubusercontent.com/assets/261579/8221738/12da47e0-1530-11e5-8113-daff936f944b.png)

From this I conclude a dev2 table is not needed, since the families shown above in green lack a dev2 table, but work in Safari.

**Comment by MrBrezina** [comment]
In other words: you proved that properly coded `deva` is necessary for Mac OS X 10.7–10.9. `dev2` is only supported from `10.10`. `dev2` is still needed for a) other applications, b) to get better shaping, esp. better control over interaction of conjuncts and matra i (ikar).

Just to be clear here. We operated with the brief that `dev2` is not needed based on some examples provided by Google. And supporting the `deva` is little backwards. I will see this fixed soon-ish.

**Comment by davelab6** [comment]
Any updates on this?

**Comment by MrBrezina** [comment]
I will get to it asap.

**Comment by MrBrezina** [comment]
Sorry it took so long.
Also, please do test it. I do not have old Mac OS X installed anywhere near.
