### ISSUE TITLE
TRADEMARKS.md file?

### ISSUE THREAD

**Issue by davelab6** [rosettatype/eczar#16]
Per the discussion in https://github.com/rosettatype/eczar/pulls, is there a trademark license available to people who need one? If so, please add a TRADEMARKS.md file explaining this :)

**Comment by MrBrezina** [comment]
I am not sure what are you talking about. There is no trademark on Eczar.

**Comment by davelab6** [comment]
Sorry I had the wrong link, correct one is https://github.com/rosettatype/eczar/pull/1#issuecomment-61941133

**Comment by MrBrezina** [comment]
Yep. As clarified, there is no trademark.

**Comment by davelab6** [comment]
Thanks!
