### ISSUE TITLE
all the .otf files labelled as regular.

### ISSUE THREAD

**Issue by demoy** [rosettatype/eczar#17]
I am unable to the .otf as all use the label "regualr", installing one prevents installing the other. The ttf don't demonstrate this problem.
![screenshot_20170328_103930](https://cloud.githubusercontent.com/assets/2396524/24414141/1ed1a9f8-13a3-11e7-9e70-7190ee3f3154.png)

I am using KDE under linux, if thats significant.

**Comment by MrBrezina** [comment]
If the TTFs work well, then the problem might be in the application, not in the fonts. In terms of naming both, OTFs and TTFs, are produced identically and seem correct on our side. What is unusual about the Eczar fonts is that they provide alternative font/style names for different languages. Maybe it is upsetting KDE/Font Viewer?

**Comment by demoy** [comment]
Maybe.
