### ISSUE TITLE
Eczar weights in oft-format have wrong "weight class" in OS/2

### ISSUE THREAD

**Issue by demoy** [rosettatype/eczar#18]
Related to issue #17, I really like this font so I decided to try fontforge to find out why all weight in the oft format are regular in my linux desktop enviroment. I found the issue:
![screenshot_20170419_114134](https://cloud.githubusercontent.com/assets/2396524/25191579/ad94f88a-24f5-11e7-83fa-6ee8cdc6f14f.png)

I compare this the ttf format:
![screenshot_20170419_114920](https://cloud.githubusercontent.com/assets/2396524/25191749/49254520-24f6-11e7-8d6a-ed7efaefed75.png)
Furthermore I change the weight class value to bold in the odt file and the issue was resolved.

 I don't how you would solve this if you use a different editor.

**Comment by MrBrezina** [comment]
Of course you are right. I did not spot this earlier because I was looking at different repo (Yrsa & Rasa) where it is correct! Sorry for this taking so long to fix.

**Comment by MrBrezina** [comment]
@demoy you can download the fonts now from: https://github.com/rosettatype/eczar/releases
thank you for your help

**Comment by demoy** [comment]
@MrBrezina  the regular fonts are missing in your release. Thanks.

**Comment by MrBrezina** [comment]
@demoy try now
