### ISSUE TITLE
ँ after ै and  ौ  rendered incorrectly

### ISSUE THREAD

**Issue by pranphy** [rosettatype/eczar#20]
The combination of    ै  + ँ is rendered as if it were a combination of  ‍ै + ं . Similarly for ौ + ँ . These two combinations are different at least for Nepali(नेपाली) language.

**Comment by MrBrezina** [comment]
You are right of course. Did not get to fix it here, yet. Will do eventually.

**Comment by pranphy** [comment]
Has there been a fix to this?

**Comment by MrBrezina** [comment]
Give us some time to recompile the fonts. I will comment here when they are ready.
